export default {
  login: "Muba-rak",
  id: 94548406,
  node_id: "U_kgDOBaKxtg",
  avatar_url: "https://avatars.githubusercontent.com/u/94548406?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Muba-rak",
  html_url: "https://github.com/Muba-rak",
  followers_url: "https://api.github.com/users/Muba-rak/followers",
  following_url: "https://api.github.com/users/Muba-rak/following{/other_user}",
  gists_url: "https://api.github.com/users/Muba-rak/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Muba-rak/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Muba-rak/subscriptions",
  organizations_url: "https://api.github.com/users/Muba-rak/orgs",
  repos_url: "https://api.github.com/users/Muba-rak/repos",
  events_url: "https://api.github.com/users/Muba-rak/events{/privacy}",
  received_events_url: "https://api.github.com/users/Muba-rak/received_events",
  type: "User",
  site_admin: false,
  name: "Mubarak Oladapo",
  company: "Tech Studio Academy",
  blog: "",
  location: "Lagos, Nigeria",
  email: null,
  hireable: null,
  bio: "Fullstack developer working with JavaScript/Typescript, React, Nodejs, Express.",
  twitter_username: "i_am__mubarak",
  public_repos: 52,
  public_gists: 0,
  followers: 10,
  following: 15,
  created_at: "2021-11-17T15:02:45Z",
  updated_at: "2023-08-19T06:31:26Z",
};
