export default [
  {
    login: "ayoawos",
    id: 77253740,
    node_id: "MDQ6VXNlcjc3MjUzNzQw",
    avatar_url: "https://avatars.githubusercontent.com/u/77253740?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ayoawos",
    html_url: "https://github.com/ayoawos",
    followers_url: "https://api.github.com/users/ayoawos/followers",
    following_url:
      "https://api.github.com/users/ayoawos/following{/other_user}",
    gists_url: "https://api.github.com/users/ayoawos/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ayoawos/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ayoawos/subscriptions",
    organizations_url: "https://api.github.com/users/ayoawos/orgs",
    repos_url: "https://api.github.com/users/ayoawos/repos",
    events_url: "https://api.github.com/users/ayoawos/events{/privacy}",
    received_events_url: "https://api.github.com/users/ayoawos/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "strangeyt-1",
    id: 89660876,
    node_id: "MDQ6VXNlcjg5NjYwODc2",
    avatar_url: "https://avatars.githubusercontent.com/u/89660876?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/strangeyt-1",
    html_url: "https://github.com/strangeyt-1",
    followers_url: "https://api.github.com/users/strangeyt-1/followers",
    following_url:
      "https://api.github.com/users/strangeyt-1/following{/other_user}",
    gists_url: "https://api.github.com/users/strangeyt-1/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/strangeyt-1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/strangeyt-1/subscriptions",
    organizations_url: "https://api.github.com/users/strangeyt-1/orgs",
    repos_url: "https://api.github.com/users/strangeyt-1/repos",
    events_url: "https://api.github.com/users/strangeyt-1/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/strangeyt-1/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "habeebgith",
    id: 91540103,
    node_id: "U_kgDOBXTKhw",
    avatar_url: "https://avatars.githubusercontent.com/u/91540103?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/habeebgith",
    html_url: "https://github.com/habeebgith",
    followers_url: "https://api.github.com/users/habeebgith/followers",
    following_url:
      "https://api.github.com/users/habeebgith/following{/other_user}",
    gists_url: "https://api.github.com/users/habeebgith/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/habeebgith/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/habeebgith/subscriptions",
    organizations_url: "https://api.github.com/users/habeebgith/orgs",
    repos_url: "https://api.github.com/users/habeebgith/repos",
    events_url: "https://api.github.com/users/habeebgith/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/habeebgith/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ndujesco",
    id: 92054718,
    node_id: "U_kgDOBXykvg",
    avatar_url: "https://avatars.githubusercontent.com/u/92054718?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ndujesco",
    html_url: "https://github.com/ndujesco",
    followers_url: "https://api.github.com/users/ndujesco/followers",
    following_url:
      "https://api.github.com/users/ndujesco/following{/other_user}",
    gists_url: "https://api.github.com/users/ndujesco/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ndujesco/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ndujesco/subscriptions",
    organizations_url: "https://api.github.com/users/ndujesco/orgs",
    repos_url: "https://api.github.com/users/ndujesco/repos",
    events_url: "https://api.github.com/users/ndujesco/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ndujesco/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mannydrey",
    id: 94547386,
    node_id: "U_kgDOBaKtug",
    avatar_url: "https://avatars.githubusercontent.com/u/94547386?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mannydrey",
    html_url: "https://github.com/mannydrey",
    followers_url: "https://api.github.com/users/mannydrey/followers",
    following_url:
      "https://api.github.com/users/mannydrey/following{/other_user}",
    gists_url: "https://api.github.com/users/mannydrey/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mannydrey/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mannydrey/subscriptions",
    organizations_url: "https://api.github.com/users/mannydrey/orgs",
    repos_url: "https://api.github.com/users/mannydrey/repos",
    events_url: "https://api.github.com/users/mannydrey/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mannydrey/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Larrydon17",
    id: 94547520,
    node_id: "U_kgDOBaKuQA",
    avatar_url: "https://avatars.githubusercontent.com/u/94547520?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Larrydon17",
    html_url: "https://github.com/Larrydon17",
    followers_url: "https://api.github.com/users/Larrydon17/followers",
    following_url:
      "https://api.github.com/users/Larrydon17/following{/other_user}",
    gists_url: "https://api.github.com/users/Larrydon17/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Larrydon17/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Larrydon17/subscriptions",
    organizations_url: "https://api.github.com/users/Larrydon17/orgs",
    repos_url: "https://api.github.com/users/Larrydon17/repos",
    events_url: "https://api.github.com/users/Larrydon17/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Larrydon17/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AyorindeAjayi",
    id: 96055048,
    node_id: "U_kgDOBbmvCA",
    avatar_url: "https://avatars.githubusercontent.com/u/96055048?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AyorindeAjayi",
    html_url: "https://github.com/AyorindeAjayi",
    followers_url: "https://api.github.com/users/AyorindeAjayi/followers",
    following_url:
      "https://api.github.com/users/AyorindeAjayi/following{/other_user}",
    gists_url: "https://api.github.com/users/AyorindeAjayi/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AyorindeAjayi/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/AyorindeAjayi/subscriptions",
    organizations_url: "https://api.github.com/users/AyorindeAjayi/orgs",
    repos_url: "https://api.github.com/users/AyorindeAjayi/repos",
    events_url: "https://api.github.com/users/AyorindeAjayi/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AyorindeAjayi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Blard-omu",
    id: 102221908,
    node_id: "U_kgDOBhfIVA",
    avatar_url: "https://avatars.githubusercontent.com/u/102221908?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Blard-omu",
    html_url: "https://github.com/Blard-omu",
    followers_url: "https://api.github.com/users/Blard-omu/followers",
    following_url:
      "https://api.github.com/users/Blard-omu/following{/other_user}",
    gists_url: "https://api.github.com/users/Blard-omu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Blard-omu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Blard-omu/subscriptions",
    organizations_url: "https://api.github.com/users/Blard-omu/orgs",
    repos_url: "https://api.github.com/users/Blard-omu/repos",
    events_url: "https://api.github.com/users/Blard-omu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Blard-omu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Makanaki011",
    id: 104405491,
    node_id: "U_kgDOBjkZ8w",
    avatar_url: "https://avatars.githubusercontent.com/u/104405491?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Makanaki011",
    html_url: "https://github.com/Makanaki011",
    followers_url: "https://api.github.com/users/Makanaki011/followers",
    following_url:
      "https://api.github.com/users/Makanaki011/following{/other_user}",
    gists_url: "https://api.github.com/users/Makanaki011/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Makanaki011/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Makanaki011/subscriptions",
    organizations_url: "https://api.github.com/users/Makanaki011/orgs",
    repos_url: "https://api.github.com/users/Makanaki011/repos",
    events_url: "https://api.github.com/users/Makanaki011/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Makanaki011/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Ebuka-Chucks",
    id: 133223495,
    node_id: "U_kgDOB_DURw",
    avatar_url: "https://avatars.githubusercontent.com/u/133223495?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ebuka-Chucks",
    html_url: "https://github.com/Ebuka-Chucks",
    followers_url: "https://api.github.com/users/Ebuka-Chucks/followers",
    following_url:
      "https://api.github.com/users/Ebuka-Chucks/following{/other_user}",
    gists_url: "https://api.github.com/users/Ebuka-Chucks/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Ebuka-Chucks/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Ebuka-Chucks/subscriptions",
    organizations_url: "https://api.github.com/users/Ebuka-Chucks/orgs",
    repos_url: "https://api.github.com/users/Ebuka-Chucks/repos",
    events_url: "https://api.github.com/users/Ebuka-Chucks/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Ebuka-Chucks/received_events",
    type: "User",
    site_admin: false,
  },
];
